### ISSUE TITLE
[FEAT]: Créer le service enregistrer les sites

### ISSUE THREAD

**Issue by fagathe-dev** [fagathe-dev/tracking#50]
- [x] ajouter un nouveau site #53 
- [x] modifier un site #54 
- [x] supprimer un site #55 
- [x] lister avec pagination #66 
- [x] activer/désactiver un site #56
